# 4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

**Problem - 1: Array Creation:**

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [1]:
import numpy as np

empty = np.empty((2, 2))
allOne = np.ones((4, 2))
fill = np.full(allOne.shape, 4)
zeros = np.zeros(allOne.shape)
ones = np.ones(allOne.shape)

new_list = [1, 2, 3, 4]
array = np.array(new_list)

for index, ans in enumerate([empty, allOne, fill, zeros, ones, array]):
  print(f"Ans{index}: \n{ans}\n")

Ans0: 
[[4.81777505e-310 0.00000000e+000]
 [9.04115220e+271 1.02124020e+277]]

Ans1: 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Ans2: 
[[4 4]
 [4 4]
 [4 4]
 [4 4]]

Ans3: 
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ans4: 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Ans5: 
[1 2 3 4]



# 4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.

  {Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

array = np.arange(10, 49)
print(f"Array with values ranging from 10 to 49= \n{array}\n")

matrix = np.arange(0, 9)
matrix_1 = matrix.reshape(3, 3)
print(f"3X3 matrix with values ranging from 0 to 8= \n{matrix_1}\n")

matrix_2 = np.eye(3)
print(f"3X3 identity matrix= \n{matrix_2}\n")

arr1 = np.random.random(30)
mean_val = arr1.mean()
print(f"Random array of size 30= \n{arr1}")
print(f"Mean of the above array= {mean_val}\n")

arr2 = np.random.random((10, 10))
min_val = arr2.min()
max_val = arr2.max()
print(f"min = {min_val} and max = {max_val} of array:\n{arr2}\n")

zeros = np.zeros(10)
print(f"Orginal array = {zeros}")
zeros[4] = 1
print(f"Modified array = {zeros}\n")

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(f"Original array = {arr}")
print(f"Reversed array = {arr}\n")

border_array = np.ones((4, 4))
border_array[1:-1, 1:-1] = 0
print(f"Boarder Array = {border_array}\n")

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(f"Checkerboard Pattern =\n{checkerboard}")

Array with values ranging from 10 to 49= 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]

3X3 matrix with values ranging from 0 to 8= 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3X3 identity matrix= 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30= 
[0.4817176  0.10585686 0.48480213 0.90539494 0.32113747 0.43512937
 0.38104812 0.55854309 0.21322413 0.41527034 0.04363297 0.9250429
 0.58183378 0.22712485 0.95550969 0.04310851 0.36443174 0.59466834
 0.59055306 0.7931981  0.81171246 0.98960589 0.6723866  0.53443658
 0.46155902 0.58080945 0.71944647 0.82318936 0.81368508 0.47105336]
Mean of the above array= 0.5433037415786228

min = 0.01456594635402153 and max = 0.9984308349246475 of array:
[[0.88224893 0.67806078 0.36450761 0.74155903 0.50635539 0.13670055
  0.46030233 0.42639277 0.43404934 0.609311  ]
 [0.24456045 0.42680373 0.21547504 0.16869853 0.57892696 0.88695807
  0.01456595 0.60381171 0.10922188 0.53460253]
 [

# Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.

  {Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
x = np.array([[1, 2],[3, 5]])
y = np.array([[5, 6],[7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add = np.add(x, y)
print(f"{x} + {y} = {add}".replace("\n", " ")+"\n")

subtract = np.subtract(x, y)
print(f"{x} - {y} = {subtract}".replace("\n", " ")+"\n")

multiply = np.multiply(x, 2)
print(f"{x} X 2 = {multiply}".replace("\n", " ")+"\n")

square = np.power(y, 2)
print(f"{y} ^ 2 = {square}".replace("\n", " ")+"\n")

vandw = np.dot(v, w)
xandv = np.dot(x, v)
xandy = np.dot(x, y)
print(f"{v} dot {w} = {vandw}".replace("\n", " "))
print(f"{x} dot {v} = {xandv}".replace("\n", " "))
print(f"{x} dot {y} = {xandy}".replace("\n", " ")+"\n")

concat_row = np.concatenate((x, y), axis=1)
concat_column = np.concatenate((v, w), axis=0)
print(f"concatenating {x} and {y} along row= {concat_row}".replace("\n", " "))
print(f"concatenating {v} and {w} along column= {concat_column}".replace("\n", " ")+"\n")

# concatenate = np.concatenate((x, v), axis=0)
# print(concatenate)

'''
  We cannot concatenate arrays with different dimension.
  In this case x is 2d array and v is 1d array.So, it throws an error.
'''

[[1 2]  [3 5]] + [[5 6]  [7 8]] = [[ 6  8]  [10 13]]

[[1 2]  [3 5]] - [[5 6]  [7 8]] = [[-4 -4]  [-4 -3]]

[[1 2]  [3 5]] X 2 = [[ 2  4]  [ 6 10]]

[[5 6]  [7 8]] ^ 2 = [[25 36]  [49 64]]

[ 9 10] dot [11 12] = 219
[[1 2]  [3 5]] dot [ 9 10] = [29 77]
[[1 2]  [3 5]] dot [[5 6]  [7 8]] = [[19 22]  [50 58]]

concatenating [[1 2]  [3 5]] and [[5 6]  [7 8]] along row= [[1 2 5 6]  [3 5 7 8]]
concatenating [ 9 10] and [11 12] along column= [ 9 10 11 12]



'\n  We cannot concatenate arrays with different dimension.\n  In this case x is 2d array and v is 1d array.So, it throws an error.\n'

# Problem - 4: Matrix Operations:

For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A<sup>−1</sup> = I.
2. Prove AB ̸= BA.
3. Prove (AB)<sup>T</sup> = B<sup>T</sup>A<sup>T</sup>


Solve the following system of Linear equation using Inverse Methods.

  2x − 3y + z = −1
  
  x − y + 2z = −3
  
  3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_Inverse = np.linalg.inv(A)
Result = np.dot(A, A_Inverse)

print(f"{A} * {A_Inverse} = {Result.round().astype(int)}".replace("\n", " ")+"\n")

AB = np.dot(A, B)
BA = np.dot(B, A)
print(f"{AB} != {BA}".replace("\n", " ")+"\n")

A_T = np.transpose(A)
B_T = np.transpose(B)
AB_T = np.transpose(AB)
BT_AT = np.dot(B_T, A_T)
print(f"{AB_T} = {BT_AT}".replace("\n", " ")+"\n")

# Linear equation
a = [[2, -3, 1],[1, -1, 2],[3, 1, -1]]
b = [-1, -3, 9]

a_Inverse = np.linalg.inv(a)      #a^(-1)
X = np.dot(a_Inverse, b)          #X = A^(-1).B   [AX = B]

print(f"A = {a}")
print(f"B = {b}")
print(f"A^(-1) = {a_Inverse}")
print(f"X = {X}")

[[3 4]  [7 8]] * [[-2.    1.  ]  [ 1.75 -0.75]] = [[1 0]  [0 1]]

[[23 13]  [51 29]] != [[36 44]  [13 16]]

[[23 51]  [13 29]] = [[23 51]  [13 29]]

A = [[2, -3, 1], [1, -1, 2], [3, 1, -1]]
B = [-1, -3, 9]
A^(-1) = [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
X = [ 2.  1. -2.]


# 4.2 Experiment: How Fast is Numpy?

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:

  • Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
  and Print the time taken for this operation.
  • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
  operation.
2. Element-wise Multiplication

  • Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
  sure and Print the time taken for this operation.

  • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
  operation.
3. Dot Product

  • Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
  Print the time taken for this operation.
  • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
  operation.
4. Matrix Multiplication

  • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
  and print the time taken for this operation.

  • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
  sure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

size = 1000000

list1 = [i for i in range(size)]
list2 = [j for j in range(size)]

array1 = np.array(list1)
array2 = np.array(list2)

# Adding
start = time.time()
add_list = [list1[i] + list2[i] for i in range(size)]
add_list_time = time.time() - start
print(f"Time taken for adding 2 lists = {add_list_time}")

start = time.time()
add_array = array1 + array2
add_array_time = time.time() - start
print(f"Time taken for adding 2 arrays = {add_array_time}\n")

# Multiplication
start = time.time()
multiply_list = [list1[i] * list2[i] for i in range(size)]
multiply_list_time = time.time() - start
print(f"Time taken for multiplying 2 lists = {multiply_list_time}")

start = time.time()
multiply_array = array1 * array2
multiply_array_time = time.time() - start
print(f"Time taken for multiplying 2 arrays = {multiply_array_time}\n")

# Dot Product
start = time.time()
dot_list = sum([list1[i] * list2[i] for i in range(size)])
dot_list_time = time.time() - start
print(f"Time taken to caluclate the dot product of 2 lists = {dot_list_time}")

start = time.time()
dot_array = np.dot(array1,array2)
dot_array_time = time.time() - start
print(f"Time taken to calculate the dot product of 2 arrays = {dot_array_time}\n")

# Matrix Multiplication
matrix1 = [[1]* 1000 for _ in range(1000)]
matrix2 = [[1]* 1000 for _ in range(1000)]

matrix2_T = [[matrix2[j][i] for j in range(1000)] for i in range(1000)]

start = time.time()

result = []
for i in range(1000):  #row
  new_row = []
  for j in range(1000):  #column
    total = 0
    for k in range(1000):  #each element
      total += matrix1[i][k] * matrix2_T[j][k]
    new_row.append(total)
  result.append(new_row)

list_time = time.time() - start

print(f"Time taken for Matrix Multiplication of lists = {list_time}")

mat1 = np.ones((1000, 1000))
mat2 = np.ones((1000, 1000))

start = time.time()
result = np.dot(mat1, mat2)
array_time = time.time() - start

print(f"Time taken for Matrix Multiplication of arrays = {array_time}")

Time taken for adding 2 lists = 0.18347549438476562
Time taken for adding 2 arrays = 0.002452850341796875

Time taken for multiplying 2 lists = 0.16131186485290527
Time taken for multiplying 2 arrays = 0.0024063587188720703

Time taken to caluclate the dot product of 2 lists = 0.18436121940612793
Time taken to calculate the dot product of 2 arrays = 0.0018792152404785156

Time taken for Matrix Multiplication of lists = 331.55979084968567
Time taken for Matrix Multiplication of arrays = 0.06771564483642578
